services:
  db:
    image: postgres:15
    container_name: talentbinder
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: talentBinder_db
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
